/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DangoShopMessages231: typeof import('./src/exercises/2.3.1-store-state/.internal/DangoShopMessages-231.vue')['default']
    DangoStick231: typeof import('./src/exercises/2.3.1-store-state/.internal/DangoStick-231.vue')['default']
    RouterLink: typeof import('vue-router/auto')['RouterLink']
    RouterView: typeof import('vue-router/auto')['RouterView']
  }
}
