/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DangoShopMessages: typeof import('./src/exercises/2.3.1-store-state/.internal/DangoShopMessages.vue')['default']
    DangoStick: typeof import('./src/exercises/2.3.1-store-state/.internal/DangoStick.vue')['default']
    RouterLink: typeof import('vue-router/auto')['RouterLink']
    RouterView: typeof import('vue-router/auto')['RouterView']
  }
}
