name: test

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'src/**/instructions.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run build # generates the types
      - run: pnpm run internal:test:types
      - run: pnpm run internal:test
